#!/usr/bin/env python3
"""Read-only source/environment checks; never load models or connect a robot."""
from __future__ import annotations

import argparse
import ast
import importlib.util
from pathlib import Path
import re
import subprocess
import sys
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--environment', action='store_true', help='Also check runtime module availability')
    args = parser.parse_args()
    errors = []
    shells = sorted((ROOT / 'scripts').rglob('*.sh'))
    for path in shells:
        result = subprocess.run(['bash', '-n', str(path)], capture_output=True, text=True)
        if result.returncode:
            errors.append(result.stderr.strip())
    sources = [*ROOT.joinpath('scripts').rglob('*.py'), *ROOT.joinpath('steering').rglob('*.py')]
    sources += [ROOT / 'hardware/my_device/macros.py', ROOT / 'hardware/flexiv/robot.py', ROOT / 'openpi/src/openpi/training/config.py']
    changed = subprocess.check_output(['git', 'diff', 'HEAD', '--name-only', '--diff-filter=ACMR'], cwd=ROOT, text=True)
    sources = sorted(set(sources) | {ROOT / name for name in changed.splitlines() if name.endswith('.py')})
    for path in sources:
        try:
            ast.parse(path.read_text(), filename=str(path))
        except (SyntaxError, UnicodeError) as exc:
            errors.append(str(exc))
    docs = [ROOT / 'README.md', ROOT / 'web_steer/README.md', *ROOT.joinpath('docs').rglob('*.md')]
    for path in docs:
        # Inline local links only; upstream docs and remote links are not certified here.
        for raw in re.findall(r'\]\(([^)]+)\)', path.read_text()):
            target = unquote(raw.split('#', 1)[0].split(' "', 1)[0].strip('<>'))
            if not target or re.match(r'[a-zA-Z][\w+.-]*:', target):
                continue
            if target.startswith('/') or not (path.parent / target).exists():
                errors.append(f'{path.relative_to(ROOT)}: invalid local link: {target}')
    # Every staged gitlink must have a reproducible clone source.
    index = subprocess.check_output(['git', 'ls-files', '--stage'], cwd=ROOT, text=True)
    modules = subprocess.run(['git', 'config', '--file', '.gitmodules', '--get-regexp', r'^submodule\..*\.path$'],
                             cwd=ROOT, text=True, capture_output=True)
    mapped_paths = set()
    for line in modules.stdout.splitlines():
        key, path = line.split(None, 1)
        mapped_paths.add(path)
        url = subprocess.run(['git', 'config', '--file', '.gitmodules', '--get', key[:-4] + 'url'],
                             cwd=ROOT, text=True, capture_output=True)
        if url.returncode or not url.stdout.strip():
            errors.append(f'Submodule {path} is missing its source URL')
    for line in index.splitlines():
        metadata, path = line.split('\t', 1)
        if metadata.startswith('160000 ') and path not in mapped_paths:
            errors.append(f'Gitlink {path} has no .gitmodules mapping')
        if '__pycache__/' in path or path.endswith(('.pyc', '.pyo')):
            errors.append(f'Generated bytecode is tracked: {path}')
    if args.environment:
        if sys.version_info[:2] != (3, 11):
            errors.append(f'Expected Python 3.11, got {sys.version.split()[0]}')
        for name in ('numpy', 'torch', 'torchvision', 'jax', 'openpi', 'openpi_client', 'accelerate', 'deepspeed', 'cv2', 'flexivrdk', 'pyrealsense2', 'pygame'):
            if importlib.util.find_spec(name) is None:
                errors.append(f'Missing runtime module: {name} (may be unnecessary on a server-only/client-only machine)')
    print(f'Checked {len(shells)} shell scripts, {len(sources)} Python files, {len(docs)} project Markdown files.')
    for error in errors:
        print(f'ERROR: {error}')
    print('NOTE: Full GPU/hardware execution and external assets are not checked. See README.md.')
    return 1 if errors else 0


if __name__ == '__main__':
    raise SystemExit(main())
